title: SurviveNTNU
baseurl: ""
markdown: kramdown
redcarpet:
    extensions: ["tables"]

fav_links:
  師大:
    link: http://www3.ntnu.edu.tw/
    image: home63.svg
  選課:
    link: http://www.ntnu.edu.tw/aa/courseweb.html
    image: pen38.svg
  圖書館:
    link: http://www.lib.ntnu.edu.tw/
    image: living1.svg
  信箱:
    link: https://webmail.ntnu.edu.tw/cgi-bin/owmmdir2/openwebmail.pl
    image: mail59.svg
  校務行政系統:
    link: http://iportal.ntnu.edu.tw/ntnu/
    image: manager3.svg
  Moodle:
    link: http://moodle.ntnu.edu.tw/
    image: users81.svg
  Moodle2:
    link: https://moodle2.ntnu.edu.tw/
    image: users81.svg

collections:
  references:
    output: true
    permalink: /:path/
