title: SurviveNTNU
baseurl: "/"
website_url: "https://survive.shida.us"
markdown: kramdown
redcarpet:
    extensions: ["tables"]
gems:
  - jekyll-coffeescript

collections:
  references:
    output: true
    permalink: /:path/
  archive:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "references"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "archive"
    values:
      layout: "page"
