title: SurviveNTNU
baseurl: ""
markdown: kramdown
redcarpet:
    extensions: ["tables"]

collections:
  references:
    output: true
    permalink: /:path/
  archive:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "references"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "archive"
    values:
      layout: "page"
