title: SurviveNTNU
baseurl: ""
markdown: kramdown
redcarpet:
    extensions: ["tables"]

collections:
  references:
    output: true
    permalink: /:path/
  archive:
    output: true
    permalink: /:path/
